# ===========================================
# DOCKER COMPOSE - DESENVOLVIMENTO LOCAL
# Link Chart Frontend - Ambiente de Desenvolvimento
# ===========================================

# Docker Compose v2 não precisa da versão

services:
  # ===========================================
  # FRONTEND - NEXT.JS
  # ===========================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - NODE_ENV=development
        - NEXT_TELEMETRY_DISABLED=1
    
    container_name: linkchartapp-frontend-dev
    
    ports:
      - "3000:3000"
    
    volumes:
      # Hot reload para desenvolvimento
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      
      # Evitar sobrescrever node_modules
      - /app/node_modules
      - /app/.next
    
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    
    env_file:
      - ../../.env.local
    
    command: npm run dev
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    networks:
      - linkchartapp-network

# ===========================================
# NETWORKS
# ===========================================
networks:
  linkchartapp-network:
    driver: bridge
    name: linkchartapp-network

# ===========================================
# VOLUMES
# ===========================================
volumes:
  node_modules:
    name: linkchartapp-frontend-node-modules
