services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    container_name: linkchartapp-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://138.197.121.81
