# 🐳 DOCKER COMPOSE - LOCAL TEST
# Configuração simplificada para testes locais

version: '3.8'

services:
  # ========================================
  # 🚀 FRONTEND APPLICATION (LOCAL)
  # ========================================
  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.prod
      args:
        - NODE_ENV=production
    
    container_name: linkcharts-frontend-local
    
    restart: unless-stopped
    
    ports:
      - "3000:80"
    
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
    
    volumes:
      # Logs persistentes
      - ../logs/nginx:/var/log/nginx
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
