import type { Metadata } from "next";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import {
  buildAnalyticsPageSchema,
  serializeJsonLd,
} from "@/lib/seo/structuredData";

interface Props {
  params: Promise<{ slug: string }>;
}

/**
 * Allowed character set for a public link slug. Slugs are URL-path segments
 * generated by the backend (alphanumerics, hyphen, underscore). Anything
 * outside this set is treated as a malformed/hostile request and 404s before
 * the value reaches an upstream fetch or a JSON-LD `<script>` injection.
 */
const SLUG_PATTERN = /^[a-zA-Z0-9_-]+$/;

/**
 * Builds the localized copy set consumed by {@link generateMetadata}.
 *
 * pt-BR is the default on purpose: these pages are the product's viral loop —
 * shared to a Brazilian audience (mostly via WhatsApp), and neither social
 * scrapers nor first-time visitors carry the `i18nextLng` cookie, so the
 * cookieless path is exactly the one that feeds the OG preview. English is
 * strictly opt-in via the same cookie the client-side language toggle writes.
 *
 * @param isEn - whether the `i18nextLng` cookie resolved to English.
 * @param slug - public link slug, already validated against `SLUG_PATTERN`.
 * @param clicks - total tracked clicks reported by the public analytics API.
 * @returns localized strings for the page title/description, Open Graph and
 *   Twitter Card metadata.
 */
function buildMetaCopy(isEn: boolean, slug: string, clicks: number) {
  if (isEn) {
    const clickLabel = clicks === 1 ? "click" : "clicks";
    return {
      title: `${slug} — Link Analytics`,
      description: `Public analytics for the link "${slug}". ${clicks} total ${clickLabel} tracked.`,
      ogTitle: `${slug} — Link Analytics | Link Charts`,
      twitterDescription: `${clicks} ${clickLabel} tracked for this link.`,
      ogImageAlt: "Link Charts Analytics",
    };
  }
  const clickLabel = clicks === 1 ? "clique registrado" : "cliques registrados";
  return {
    title: `${slug} — Estatísticas do Link`,
    description: `Estatísticas públicas do link "${slug}". ${clicks} ${clickLabel} no total.`,
    ogTitle: `${slug} — Estatísticas do Link | Link Charts`,
    twitterDescription: `${clicks} ${clickLabel} neste link.`,
    ogImageAlt: "Estatísticas do Link Charts",
  };
}

/**
 * Generates language-aware metadata (title/description, Open Graph and Twitter
 * Card) for a public analytics page by reading the `i18nextLng` cookie
 * server-side — the same cookie `detectAndApplyLanguage()` reads client-side,
 * so SSR metadata and hydrated copy agree on the language. Mirrors the
 * cookie-based pattern of `app/(auth)/sign-in/page.tsx`; pt-BR is the default
 * for the cookieless case (OG scrapers and cold opens of shared links).
 *
 * The analytics fetch keeps `revalidate: 300` (deduped with the page render)
 * and the route stays `noindex, follow` — per-slug pages are thin content and
 * must not compete with the home and /shorter pages in the index.
 *
 * @param props - route props carrying the `slug` params promise.
 * @returns the resolved Next.js {@link Metadata} for the page.
 */
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  if (!SLUG_PATTERN.test(slug)) {
    notFound();
  }
  const apiUrl = process.env.API_URL ?? "http://localhost:8000";
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://linkcharts.com.br";
  const res = await fetch(`${apiUrl}/api/public/analytics/${slug}`, {
    next: { revalidate: 300 },
  }).catch(() => null);

  const data = res?.ok ? await res.json() : null;
  const clicks = data?.data?.total_clicks ?? 0;

  const cookieStore = await cookies();
  const isEn = cookieStore.get("i18nextLng")?.value === "en";
  const copy = buildMetaCopy(isEn, slug, clicks);

  const ogImage = {
    url: `${appUrl}/og-default.png`,
    width: 1200,
    height: 630,
    alt: copy.ogImageAlt,
  };

  return {
    title: copy.title,
    description: copy.description,
    alternates: {
      canonical: `${appUrl}/public-analytics/${slug}`,
    },
    // Per-slug analytics pages can multiply quickly and offer thin content
    // for users that didn't create the link. We allow link equity to flow
    // (follow) but keep them out of the index to protect SEO of the home
    // and /shorter pages.
    robots: {
      index: false,
      follow: true,
      googleBot: { index: false, follow: true },
    },
    openGraph: {
      title: copy.ogTitle,
      description: copy.description,
      type: "website",
      url: `${appUrl}/public-analytics/${slug}`,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title: copy.title,
      description: copy.twitterDescription,
      images: [`${appUrl}/og-default.png`],
    },
  };
}

export default async function PublicAnalyticsPage({ params }: Props) {
  const { slug } = await params;
  if (!SLUG_PATTERN.test(slug)) {
    notFound();
  }
  const apiUrl = process.env.API_URL ?? "http://localhost:8000";

  // Prefetch both payloads server-side (the analytics endpoint is also fetched
  // by generateMetadata — Next dedupes identical requests) and hand them to the
  // client as React Query `initialData` so it doesn't refetch on first paint.
  const [analyticsRes, linkRes] = await Promise.all([
    fetch(`${apiUrl}/api/public/analytics/${slug}`, {
      next: { revalidate: 300 },
    }).catch(() => null),
    fetch(`${apiUrl}/api/public/link/${slug}`, {
      next: { revalidate: 300 },
    }).catch(() => null),
  ]);
  const analyticsJson = analyticsRes?.ok ? await analyticsRes.json() : null;
  const linkJson = linkRes?.ok ? await linkRes.json() : null;
  const initialAnalyticsData = analyticsJson?.data ?? null;
  const initialLinkData = linkJson?.data ?? null;

  const clicks = initialAnalyticsData?.total_clicks ?? 0;
  const schema = buildAnalyticsPageSchema(slug, slug, clicks);

  const { PublicAnalyticsPageContent } = await import(
    "@/features/public-analytics"
  );

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: serializeJsonLd(schema) }}
      />
      <PublicAnalyticsPageContent
        slug={slug}
        initialLinkData={initialLinkData}
        initialAnalyticsData={initialAnalyticsData}
      />
    </>
  );
}
