import type { Metadata } from "next";
import { notFound } from "next/navigation";
import {
  buildAnalyticsPageSchema,
  serializeJsonLd,
} from "@/lib/seo/structuredData";

interface Props {
  params: Promise<{ slug: string }>;
}

/**
 * Allowed character set for a public link slug. Slugs are URL-path segments
 * generated by the backend (alphanumerics, hyphen, underscore). Anything
 * outside this set is treated as a malformed/hostile request and 404s before
 * the value reaches an upstream fetch or a JSON-LD `<script>` injection.
 */
const SLUG_PATTERN = /^[a-zA-Z0-9_-]+$/;

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  if (!SLUG_PATTERN.test(slug)) {
    notFound();
  }
  const apiUrl = process.env.API_URL ?? "http://localhost:8000";
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://linkcharts.com.br";
  const res = await fetch(`${apiUrl}/api/public/analytics/${slug}`, {
    next: { revalidate: 300 },
  }).catch(() => null);

  const data = res?.ok ? await res.json() : null;
  const clicks = data?.data?.total_clicks ?? 0;
  const ogImage = {
    url: `${appUrl}/og-default.png`,
    width: 1200,
    height: 630,
    alt: "Link Charts Analytics",
  };

  return {
    title: `${slug} — Link Analytics`,
    description: `Public analytics for the link "${slug}". ${clicks} total clicks tracked.`,
    alternates: {
      canonical: `${appUrl}/public-analytics/${slug}`,
    },
    // Per-slug analytics pages can multiply quickly and offer thin content
    // for users that didn't create the link. We allow link equity to flow
    // (follow) but keep them out of the index to protect SEO of the home
    // and /shorter pages.
    robots: {
      index: false,
      follow: true,
      googleBot: { index: false, follow: true },
    },
    openGraph: {
      title: `${slug} — Link Analytics | Link Charts`,
      description: `Public analytics for the link "${slug}". ${clicks} total clicks tracked.`,
      type: "website",
      url: `${appUrl}/public-analytics/${slug}`,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title: `${slug} — Link Analytics`,
      description: `${clicks} clicks tracked for this link.`,
      images: [`${appUrl}/og-default.png`],
    },
  };
}

export default async function PublicAnalyticsPage({ params }: Props) {
  const { slug } = await params;
  if (!SLUG_PATTERN.test(slug)) {
    notFound();
  }
  const apiUrl = process.env.API_URL ?? "http://localhost:8000";

  // Prefetch both payloads server-side (the analytics endpoint is also fetched
  // by generateMetadata — Next dedupes identical requests) and hand them to the
  // client as React Query `initialData` so it doesn't refetch on first paint.
  const [analyticsRes, linkRes] = await Promise.all([
    fetch(`${apiUrl}/api/public/analytics/${slug}`, {
      next: { revalidate: 300 },
    }).catch(() => null),
    fetch(`${apiUrl}/api/public/link/${slug}`, {
      next: { revalidate: 300 },
    }).catch(() => null),
  ]);
  const analyticsJson = analyticsRes?.ok ? await analyticsRes.json() : null;
  const linkJson = linkRes?.ok ? await linkRes.json() : null;
  const initialAnalyticsData = analyticsJson?.data ?? null;
  const initialLinkData = linkJson?.data ?? null;

  const clicks = initialAnalyticsData?.total_clicks ?? 0;
  const schema = buildAnalyticsPageSchema(slug, slug, clicks);

  const { PublicAnalyticsPageContent } = await import(
    "@/features/public-analytics"
  );

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: serializeJsonLd(schema) }}
      />
      <PublicAnalyticsPageContent
        slug={slug}
        initialLinkData={initialLinkData}
        initialAnalyticsData={initialAnalyticsData}
      />
    </>
  );
}
